{
 "title": "nodes",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "label_values(slurm_stats_server_threads, cluster)"
   },
   {
    "name": "nodeset",
    "query": "label_values(slurm_node_nodes,nodes)"
   }
  ]
 },
 "panels": [
  {
   "title": "Node count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(slurm_node_nodes{cluster=\"$cluster\",nodes=~\"$nodeset\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "CPU count (cores)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(slurm_node_cpus{cluster=\"$cluster\",nodes=~\"$nodeset\"}) by (state)",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "sum(slurm_node_load{cluster=\"$cluster\",nodes=~\"$nodeset\"})",
     "legendFormat": "loadavg"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(slurm_node_bytes{cluster=\"$cluster\",nodes=~\"$nodeset\"}) by (state)",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "sum(slurm_node_used_bytes{cluster=\"$cluster\",nodes=~\"$nodeset\"})",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "GPUs",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(slurm_node_gpus{cluster=\"$cluster\",nodes=~\"$nodeset\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  }
 ]
}