{
 "title": "queued",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" },
   { "name": "grouping", "query": "account,partition,user" }
  ]
 },
 "panels": [
  {
   "title": "Job counts",
   "type": "table-old",
   "description": "click on zoom buttons to filter",
   "gridPos": { "h": 48, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(slurm_job_count{state=\"pending\"}) by (account,partition,user)",
     "legendFormat": "jobs"
    }
   ]
  },
  {
   "title": "Job count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(slurm_job_count{state=\"pending\"}) by ($grouping)",
     "legendFormat": "{{$grouping}}"
    }
   ]
  },
  {
   "title": "Node count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(slurm_job_nodes{state=\"pending\"}) by ($grouping)",
     "legendFormat": "{{$grouping}}"
    }
   ]
  },
  {
   "title": "CPU count (cores)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(slurm_job_cpus{state=\"pending\"}) by ($grouping)",
     "legendFormat": "{{$grouping}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(slurm_job_bytes{state=\"pending\"}) by ($grouping)",
     "legendFormat": "{{$grouping}}"
    }
   ]
  },
  {
   "title": "GPUs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(slurm_job_gpus{state=\"pending\"}) by ($grouping)",
     "legendFormat": "{{$grouping}}"
    }
   ]
  },
  {
   "title": "Total queue wait time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 40 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(slurm_job_seconds{state=\"pending\"}) by ($grouping)",
     "legendFormat": "{{$grouping}}"
    }
   ]
  }
 ]
}