{
 "title": "running",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" },
   { "name": "grouping", "query": "nodes,account,partition,user" }
  ]
 },
 "panels": [
  {
   "title": "Jobs",
   "type": "table-old",
   "description": "click on zoom buttons to filter",
   "gridPos": { "h": 56, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(slurm_job_count{state=\"running\"}) by (account,user,partition)",
     "legendFormat": "jobs"
    },
    {
     "expr": "sum(slurm_job_nodes{state=\"running\"}) by (account,user,partition)",
     "legendFormat": "nodes"
    },
    {
     "expr": "(sum(slurm_job_load) by (account,user,partition))/(sum(slurm_job_cpus{state=\"running\"}) by (account,user,partition))",
     "legendFormat": "load"
    },
    {
     "expr": "sum(slurm_job_used_bytes) by (account,user,partition)",
     "legendFormat": "memory"
    }
   ]
  },
  {
   "title": "Job count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(slurm_job_count{state=\"running\"}) by ($grouping)",
     "legendFormat": "{{$grouping}}"
    }
   ]
  },
  {
   "title": "Node count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(slurm_job_nodes{state=\"running\"}) by ($grouping)",
     "legendFormat": "{{$grouping}}"
    }
   ]
  },
  {
   "title": "CPU count (cores)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(slurm_job_cpus{state=\"running\"}) by ($grouping)",
     "legendFormat": "{{$grouping}}"
    },
    {
     "expr": "sum(slurm_job_load) by ($grouping)",
     "legendFormat": "{{$grouping}} loadavg"
    }
   ]
  },
  {
   "title": "Average CPU load (efficiency)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 24 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(slurm_job_load) by ($grouping))/(sum(slurm_job_cpus{state=\"running\"}) by ($grouping))",
     "legendFormat": "{{$grouping}}"
    }
   ]
  },
  {
   "title": "Cumulative CPU time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(slurm_job_seconds{state=\"running\"}*slurm_job_cpus{state=\"running\"}) by ($grouping)",
     "legendFormat": "{{$grouping}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(slurm_job_bytes{state=\"running\"}) by ($grouping)",
     "legendFormat": "{{$grouping}}"
    },
    {
     "expr": "sum(slurm_job_used_bytes) by ($grouping)",
     "legendFormat": "{{$grouping}} used"
    }
   ]
  },
  {
   "title": "GPUs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(slurm_job_gpus{state=\"running\"}) by ($grouping)",
     "legendFormat": "{{$grouping}}"
    }
   ]
  }
 ]
}